### ISSUE TITLE
Trying to use HaltonSequences for Julia 1.7.1 gives error 

### ISSUE THREAD

**Issue by Volodymyr-Y** [tobydriscoll/HaltonSequences.jl#6]
I'm new to Julia, maybe there is something wrong with my system and not the package, but here is what I get

ERROR: Failed to precompile HaltonSequences [13907d55-377f-55d6-a9d6-25ac19e11b95] to C:\Users\Main_User\.julia\compiled\v1.7\HaltonSequences\jl_6446.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base .\loading.jl:1466
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1410
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1120
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:1013
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:997

**Comment by tobydriscoll** [comment]
I just tried it on a fresh copy of v1.8.5 without trouble (on a mac, though I can't see why that would matter at all).

You could try installing the package in a new environment. Suppose that `C:\Users\Joe\tmp` is some folder you don't care about. You do
```julia
import Pkg
Pkg.activate("C:\Users\Joe\tmp")
Pkg.add("HaltonSequences")
using HaltonSequences
```
If that is successful, it could be that your main environment has gotten corrupted. In that case you can wipe out everything in  the `compiled\v1.7` tree and it will start precompiling everything from scratch in the next session. Or just delete all of `.julia` and reinstall packages one by one.

If the problem persists, please post the contents of the result from `Pkg.status()`.

**Comment by Volodymyr-Y** [comment]
Thank you !
