### ISSUE TITLE
Release HaltonSequences@0.2.0

### ISSUE THREAD

**Issue by sathvikbhagavan** [tobydriscoll/HaltonSequences.jl#7]
Hello, I see in the Project.toml, the version is 0.2.0, but it is not registered here: https://github.com/JuliaRegistries/General/blob/master/H/HaltonSequences/Versions.toml

Can you cut a release for it?

**Comment by sathvikbhagavan** [comment]
@tobydriscoll bump on this

**Comment by tobydriscoll** [comment]
Done.
